
CREATE TABLE Parts (
    id SERIAL PRIMARY KEY,
    name TEXT UNIQUE NOT NULL,
    type TEXT CHECK (type IN ('FH_Part', 'IT_Part', 'FHIT_Part')) NOT NULL,
    fh_inspect INTEGER CHECK (fh_inspect >= 0) DEFAULT NULL,
    it_inspect INTEGER CHECK (it_inspect >= 0) DEFAULT NULL
);


INSERT INTO Parts (name, type, fh_inspect, it_inspect) VALUES
('Engine Oil Filter', 'FH_Part', 500, NULL),
('Hydraulic Pump', 'IT_Part', NULL, 180),
('Landing Gear Assembly', 'FHIT_Part', 1000, 365),
('Oxygen Cylinder', 'IT_Part', NULL, 730),
('Turbine Blade', 'FH_Part', 2000, NULL),
('Fuel Injector', 'FH_Part', 1200, NULL),
('Cabin Air Filter', 'IT_Part', NULL, 90),
('Avionics Battery', 'FHIT_Part', 800, 180),
('Brake Pad', 'FH_Part', 1500, NULL),
('Propeller Blade', 'FH_Part', 2500, NULL),
('Control Cable', 'IT_Part', NULL, 365),
('Main Rotor Blade', 'FHIT_Part', 1200, 720),
('Thrust Reverser', 'FH_Part', 3000, NULL),
('Hydraulic Actuator', 'IT_Part', NULL, 540),
('Wing Flap', 'FHIT_Part', 1800, 365),
('Cockpit Display Unit', 'IT_Part', NULL, 400),
('Pressure Relief Valve', 'FH_Part', 2200, NULL),
('Fuel Pump', 'FH_Part', 1600, NULL),
('Flight Control Computer', 'IT_Part', NULL, 600),
('Emergency Power Unit', 'FHIT_Part', 1400, 480),
('Engine Mount', 'FH_Part', 2700, NULL),
('Nose Wheel Steering Unit', 'IT_Part', NULL, 300),
('Anti-Ice System', 'FHIT_Part', 1300, 360),
('Pitot Tube', 'IT_Part', NULL, 250),
('Rudder Pedal Assembly', 'FH_Part', 2100, NULL),
('Electrical Bus Bar', 'IT_Part', NULL, 500),
('Cabin Pressure Regulator', 'FHIT_Part', 900, 365),
('Fuel Flow Transmitter', 'IT_Part', NULL, 450),
('Tail Boom', 'FH_Part', 3200, NULL),
('Horizontal Stabilizer', 'FH_Part', 2800, NULL),
('Air Data Computer', 'IT_Part', NULL, 550),
('Gyroscope Sensor', 'IT_Part', NULL, 400),
('Fuselage Panel', 'FH_Part', 3500, NULL),
('Landing Light', 'IT_Part', NULL, 600),
('Cooling Fan Assembly', 'FHIT_Part', 1700, 365),
('Radar Transceiver', 'IT_Part', NULL, 480),
('Thrust Vector Nozzle', 'FH_Part', 2600, NULL),
('Yaw Damper', 'IT_Part', NULL, 700),
('Fuel Control Unit', 'FHIT_Part', 1500, 400),
('Tail Rotor Gearbox', 'FH_Part', 2900, NULL),
('Pilot Seat Restraint', 'IT_Part', NULL, 550),
('Auxiliary Power Unit', 'FHIT_Part', 1100, 300),
('Wing Strut', 'FH_Part', 2300, NULL),
('Static Discharger', 'IT_Part', NULL, 100),
('Elevator Trim Tab', 'FH_Part', 2000, NULL),
('Cabin Door Lock', 'IT_Part', NULL, 450),
('Throttle Quadrant', 'FHIT_Part', 900, 250),
('Flap Actuator', 'FH_Part', 2400, NULL),
('Vortex Generator', 'IT_Part', NULL, 500);

select * from Parts
